language: generic

matrix:
  include:
    - os: linux
      env: CC=gcc CXX=g++
      env: CC=clang CXX=clang++
    - os: linux
      env: CC=gcc CXX=g++ EXTRA_FLAGS=-m32
      env: CC=clang CXX=clang++ EXTRA_FLAGS=-m32
      addons:
        apt:
          packages:
          - gcc-multilib
    - os: osx
      env: CC=clang CXX=clang++
      env: CC=clang CXX=clang++ EXTRA_FLAGS=-m32

before_script:
  - autoconf
  - ./configure${EXTRA_FLAGS:+ CC="$CC $EXTRA_FLAGS" CXX="$CXX $EXTRA_FLAGS"}
  - make -j3
  - make -j3 tests

script:
  - make check
